name: gelato-management

services:
  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: rabbitmq
    env_file:
      - ../.env
    networks:
      - gelato_network
    volumes:
      - ../rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ../rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
      - ../rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins:ro
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5

  analytics-mongodb:
    image: mongo:7.0
    container_name: analytics-mongodb
    env_file:
      - ../.env
    networks:
      - gelato_network
    volumes:
      - analytics_mongodb_data:/data/db
    restart: unless-stopped

  analytics-service:
    image: phoeng/analytics-service:1.0.0
    container_name: analytics-service
    env_file:
      - ../../analytics-service/.env
    networks:
      - gelato_network
    depends_on:
      rabbitmq:
        condition: service_healthy
      analytics-mongodb:
        condition: service_started
    restart: unless-stopped

networks:
  gelato_network:
    driver: bridge

volumes:
  rabbitmq_data:
  analytics_mongodb_data:
