name: gelato-management

services:
  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: rabbitmq
    env_file:
      - ../.env
    networks:
      - gelato_network
    volumes:
      - ../rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ../rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
      - ../rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins:ro
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  gelato_network:
    driver: bridge
    internal: true

volumes:
  rabbitmq_data:
